# image: mcr.microsoft.com/playwright:latest

# stages:
#   - test

# playwright-test:
#   stage: test
#   artifacts:
#     when: always
#     paths:
#       - playwright-report/
#       - test-results/
#     expire_in: 1 week
#   script:
#     - npm install
#     - npx playwright install
#     - npx playwright test --reporter=html --output=test-results/

stages:
  - test

playwright-tests:
  stage: test
  image: 
    name: mcr.microsoft.com/playwright:latest
    entrypoint: [""]
  script:
    - npm install
    - npx playwright install
    - npx playwright test
  artifacts:
    when: always
    # paths:
      # - tests-results/
    expire_in: 1 week
